# **************************************************************************************
# MIT License
#
# Copyright (c) 2019, 2020 Chris Reynolds
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
#  History:
#
#  Date        Author  Description
#  ----        ------  -----------
#  2020-08-22  CDR     Switch to official MariaDB, ProxySQL, and PMM docker images.
#                      - MariaDB  - mariadb:10.5.5
#                      - ProxySQL - proxysql/proxysql:2.0.13
#                      - PMM      - percona/pmm-server:2.9.1
# **************************************************************************************
version: "3.8"

secrets:
  MYSQL_ROOT_PASSWORD:
    external: true

services:
  proxysql1:
    image: proxysql/proxysql:2.0.13
    ports:
      - target: 6032
          published: 6032
          protocol: tcp
          mode: host
      - target: 6033
          published: 6033
          protocol: tcp
          mode: host
    volumes:
      - /var/lib/proxysql:/var/lib/proxysql
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512MB
        reservations:
          memory: 512MB
      placement:
        constraints:
          - node.hostname == moho

  proxysql2:
    image: proxysql/proxysql:2.0.13
    ports:
      - target: 6032
          published: 6032
          protocol: tcp
          mode: host
      - target: 6033
          published: 6033
          protocol: tcp
          mode: host
    volumes:
      - /var/lib/proxysql:/var/lib/proxysql
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512MB
        reservations:
          memory: 512MB
      placement:
        constraints:
          - node.hostname == eve

  galera1:
    image: mariadb:10.5.5
    ports:
      - target: 3306
          published: 3306
          protocol: tcp
          mode: host
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      - /mnt/backup/MariaDB-Stack/config/galera1:/etc/mysql/conf.d
      - /mnt/backup/MariaDB-Stack/initdb.d:/docker-entrypoint-initdb.d
      - /mnt/backup:/mnt/backup
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 1G
      placement:
        constraints:
          - node.hostname == moho
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
      - TZ=US/Central
    secrets:
      - MYSQL_ROOT_PASSWORD

  galera2:
    image: mariadb:10.5.5
    ports:
      - target: 3306
          published: 3306
          protocol: tcp
          mode: host
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      - /mnt/backup/MariaDB-Stack/config/galera2:/etc/mysql/conf.d
      - /mnt/backup/MariaDB-Stack/initdb.d:/docker-entrypoint-initdb.d
      - /mnt/backup:/mnt/backup
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 1G
      placement:
        constraints:
          - node.hostname == eve
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
      - TZ=US/Central
    secrets:
      - MYSQL_ROOT_PASSWORD

  galera3:
    image: mariadb:10.5.5
    ports:
      - target: 3306
          published: 3306
          protocol: tcp
          mode: host
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      - /mnt/backup/MariaDB-Stack/config/galera3:/etc/mysql/conf.d
      - /mnt/backup/MariaDB-Stack/initdb.d:/docker-entrypoint-initdb.d
      - /mnt/backup:/mnt/backup
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 1G
      placement:
        constraints:
          - node.hostname == kerbin
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
      - TZ=US/Central
    secrets:
      - MYSQL_ROOT_PASSWORD